package cn.iocoder.yudao.service.enums.upgrade;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum UpgradeDataEnum {
    SYSTEM_MENU("SYSTEM_MENU"), // 菜单
    INFRA_DATABASE_COLUMN("INFRA_DATABASE_COLUMN"),
    INFRA_DATABASE_TABLE("INFRA_DATABASE_TABLE"),
    INFRA_DATABASE_INDEX("INFRA_DATABASE_INDEX"),
    INFRA_DATABASE_MAPPING("INFRA_DATABASE_MAPPING"),
    INFRA_DATABASE_VALIDATION("INFRA_DATABASE_VALIDATION"),
    INFRA_INTERFACE_VO_CLASS("INFRA_INTERFACE_VO_CLASS"),
    INFRA_INTERFACE_MODULE("INFRA_INTERFACE_MODULE"),
    INFRA_INTERFACE("INFRA_INTERFACE"),
    INFRA_INTERFACE_PARAM("INFRA_INTERFACE_PARAM"),
    INFRA_INTERFACE_SUBCLASS("INFRA_INTERFACE_SUBCLASS"),
    INFRA_JOB("INFRA_JOB"),
    QRTZ_BLOB_TRIGGERS("QRTZ_BLOB_TRIGGERS"),
    QRTZ_CALENDARS("QRTZ_CALENDARS"),
    QRTZ_CRON_TRIGGERS("QRTZ_CRON_TRIGGERS"),
    QRTZ_FIRED_TRIGGERS("QRTZ_FIRED_TRIGGERS"),
    QRTZ_JOB_DETAILS("QRTZ_JOB_DETAILS"),
    QRTZ_LOCKS("QRTZ_LOCKS"),
    QRTZ_PAUSED_TRIGGER_GRPS("QRTZ_PAUSED_TRIGGER_GRPS"),
    QRTZ_SCHEDULER_STATE("QRTZ_SCHEDULER_STATE"),
    QRTZ_SIMPLE_TRIGGERS("QRTZ_SIMPLE_TRIGGERS"),
    QRTZ_SIMPROP_TRIGGERS("QRTZ_SIMPROP_TRIGGERS"),
    QRTZ_TRIGGERS("QRTZ_TRIGGERS"),
    ;

    /**
     * 表名
     */
    private final String table;
}
